"""Non-interactive CLI smoke tests for structure and motion tasks.

This suite intentionally performs short scientific runs. It is kept separate
from the focused CLI unit tests so maintainers can run it explicitly.
"""

import copy
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

import numpy as np
import yaml

import BUCToolkit as bt
from BUCToolkit.io import (
    Cif2Feat,
    OUTCAR2Feat,
    POSCARs2Feat,
    Xyz2Feat,
    read_mc_traj,
    read_md_traj,
    read_opt_structures,
)
from testsuite.test_apis import _untar


_HERE = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_HERE)
_INPUTS_DIR = os.path.join(_HERE, "inputs4test")
_STRUCTURES_DIR = os.path.join(_HERE, "test_structures")
_BASE_INPUT = os.path.join(_INPUTS_DIR, "cli_command_base.inp")
_CONSTRAINTS_FILE = os.path.join(_INPUTS_DIR, "cli_constraints.py")


class NonInteractiveCLICommandTests(unittest.TestCase):
    """Exercise five task runners through the one-line CLI entry point."""

    @classmethod
    def setUpClass(cls) -> None:
        """Build one reusable structure in every supported test format.

        The existing ``test_apis._untar`` helper remains the authoritative
        extraction path. Generated files are placed in the intentionally empty
        ``test_structures`` format directories and removed in ``tearDownClass``.

        Returns:
            None.

        Raises:
            RuntimeError: If an expected empty generated-file path is occupied
                or the OUTCAR archive yields no structures.
        """
        cls._temporary = tempfile.TemporaryDirectory(prefix="buctoolkit_cli_")
        cls._generated_files = []
        extracted_dir = os.path.join(cls._temporary.name, "outcars")
        _untar(extracted_dir)

        outcar_names = sorted(
            entry.name for entry in os.scandir(extracted_dir) if entry.is_file()
        )
        if len(outcar_names) == 0:
            raise RuntimeError("The OUTCAR archive did not contain any files.")

        outcar_data = OUTCAR2Feat(extracted_dir, verbose=0)
        outcar_data.read(file_list=outcar_names[:1], n_core=1)
        if len(outcar_data) == 0:
            raise RuntimeError("OUTCAR2Feat did not produce any structures.")
        cls.reference = copy.deepcopy(outcar_data[0])

        cls.vasp_dir = os.path.join(_STRUCTURES_DIR, "vasp")
        cls.cif_dir = os.path.join(_STRUCTURES_DIR, "cifs")
        cls.xyz_dir = os.path.join(_STRUCTURES_DIR, "xyz")
        cls.bs_dir = os.path.join(_STRUCTURES_DIR, "bs")
        for directory in (cls.vasp_dir, cls.cif_dir, cls.xyz_dir, cls.bs_dir):
            os.makedirs(directory, exist_ok=True)

        text_outputs = (
            (cls.vasp_dir, "cli_smoke.vasp", "POSCAR"),
            (cls.cif_dir, "cli_smoke.cif", "cif"),
            (cls.xyz_dir, "cli_smoke.xyz", "xyz"),
        )
        for directory, file_name, file_format in text_outputs:
            output_file = os.path.join(directory, file_name)
            cls._require_unused_path(output_file)
            cls.reference.write2text(
                directory,
                file_format=file_format,
                file_name_list=[file_name],
                n_core=1,
            )
            cls._generated_files.append(output_file)

        cls.input_bs = os.path.join(cls.bs_dir, "cli_input.bs")
        cls.final_bs = os.path.join(cls.bs_dir, "cli_final.bs")
        cls.displacement_bs = os.path.join(cls.bs_dir, "cli_displacement.bs")
        for output_file in (cls.input_bs, cls.final_bs, cls.displacement_bs):
            cls._require_unused_path(output_file)

        cls.reference.save(cls.input_bs, mode="w")
        final_state = copy.deepcopy(cls.reference)
        final_state.Coords[0][1, 0] += 0.02
        final_state.save(cls.final_bs, mode="w")
        displacement = copy.deepcopy(cls.reference)
        displacement.Coords[0] = final_state.Coords[0] - cls.reference.Coords[0]
        displacement.save(cls.displacement_bs, mode="w")
        cls._generated_files.extend(
            (cls.input_bs, cls.final_bs, cls.displacement_bs)
        )

        with open(_BASE_INPUT, "r", encoding="utf-8") as stream:
            cls.base_config = yaml.safe_load(stream)
        cls.base_config["MODEL_FILE"] = os.path.abspath(
            os.path.join(_INPUTS_DIR, cls.base_config["MODEL_FILE"])
        )

    @classmethod
    def tearDownClass(cls) -> None:
        """Remove only files generated by this suite.

        Returns:
            None.
        """
        for path in getattr(cls, "_generated_files", ()):
            if os.path.isdir(path) and not os.path.islink(path):
                shutil.rmtree(path)
            elif os.path.lexists(path):
                os.remove(path)
        temporary = getattr(cls, "_temporary", None)
        if temporary is not None:
            temporary.cleanup()

    @staticmethod
    def _require_unused_path(path: str) -> None:
        """Require a generated-resource path to be unused before the test.

        Args:
            path: Exact file path the suite intends to create.

        Returns:
            None.

        Raises:
            RuntimeError: If a file, directory, or symbolic link already uses
                ``path``.
        """
        if os.path.lexists(path):
            raise RuntimeError(
                f"CLI test resource path already exists and will not be overwritten: {path}"
            )

    def _read_text_structure(self, reader_type, directory: str, file_name: str):
        """Read one generated text structure with a BUCToolkit reader.

        Args:
            reader_type: ``BatchStructures`` reader class to instantiate.
            directory: Directory containing the generated file.
            file_name: File name passed to the reader.

        Returns:
            The populated reader instance.
        """
        reader = reader_type(directory, verbose=0)
        if reader_type is Cif2Feat:
            reader.read([file_name], n_core=1)
        else:
            reader.read([file_name])
        return reader

    def _assert_basic_structure_data(self, structures) -> None:
        """Check sample count, coordinate layout, and element identity.

        Args:
            structures: Populated ``BatchStructures``-compatible object.

        Returns:
            None.
        """
        self.assertGreater(len(structures), 0)
        self.assertEqual(
            np.asarray(structures.Coords[0]).shape,
            np.asarray(self.reference.Coords[0]).shape,
        )
        self.assertEqual(list(structures.Elements[0]), list(self.reference.Elements[0]))
        self.assertEqual(list(structures.Numbers[0]), list(self.reference.Numbers[0]))

    def _write_task_config(self, task: str, task_config: dict) -> tuple[str, str]:
        """Write a complete task input into the temporary test workspace.

        Args:
            task: Canonical CLI task name.
            task_config: Task-specific YAML fields.

        Returns:
            A tuple containing the input path and expected result path.
        """
        config = copy.deepcopy(self.base_config)
        config.update(task_config)
        config["TASK"] = task
        output_root = os.path.join(self._temporary.name, f"output_{task.lower()}")
        result_path = os.path.join(output_root, "result")
        config["OUTPUT_ROOT"] = output_root
        config["PREDICTIONS_SAVE_FILE"] = result_path
        input_path = os.path.join(self._temporary.name, f"{task.lower()}.inp")
        with open(input_path, "w", encoding="utf-8") as stream:
            yaml.safe_dump(config, stream, sort_keys=False)
        return input_path, result_path

    def _run_task(self, task: str, task_config: dict, result_reader):
        """Run one non-interactive command and load its binary result.

        Args:
            task: Canonical CLI task name.
            task_config: Task-specific YAML fields.
            result_reader: Callable that reads the task binary output.

        Returns:
            The populated result structure collection.

        Raises:
            AssertionError: If the command fails or does not create readable
                output.
        """
        input_path, result_path = self._write_task_config(task, task_config)
        command = (
            sys.executable,
            "-m",
            "BUCToolkit.cli.main",
            "-i",
            input_path,
        )
        completed = subprocess.run(
            command,
            cwd=_PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=300,
            check=False,
        )
        self.assertEqual(
            completed.returncode,
            0,
            msg=(
                f"Command failed: {' '.join(command)}\n"
                f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
            ),
        )
        self.assertTrue(
            os.path.isfile(result_path),
            msg=(
                f"{task} did not create {result_path}.\n"
                f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
            ),
        )
        return result_reader(result_path)

    def test_00_generated_structure_formats_round_trip(self) -> None:
        """Read back POSCAR, CIF, XYZ, and BS test resources."""
        readers = (
            self._read_text_structure(POSCARs2Feat, self.vasp_dir, "cli_smoke.vasp"),
            self._read_text_structure(Cif2Feat, self.cif_dir, "cli_smoke.cif"),
            self._read_text_structure(Xyz2Feat, self.xyz_dir, "cli_smoke.xyz"),
            bt.load(self.input_bs),
        )
        for structures in readers:
            with self.subTest(reader=type(structures).__name__):
                self._assert_basic_structure_data(structures)

    def test_opt_command(self) -> None:
        """Run a one-iteration OPT command and inspect its output."""
        result = self._run_task(
            "OPT",
            {
                "DATA_TYPE": "POSCAR",
                "DATA_PATH": self.vasp_dir,
                "RELAXATION": {
                    "ALGO": "FIRE",
                    "E_THRES": 0.0,
                    "F_THRES": 0.0,
                    "MAXITER": 1,
                    "STEPLENGTH": 0.01,
                },
            },
            read_opt_structures,
        )
        self._assert_basic_structure_data(result)

    def test_ts_command(self) -> None:
        """Run a short Dimer TS command and inspect its output."""
        result = self._run_task(
            "TS",
            {
                "DATA_TYPE": "BS",
                "DATA_PATH": self.input_bs,
                "DISPDATA_PATH": self.displacement_bs,
                "TRANSITION_STATE": {
                    "ALGO": "DIMER",
                    "X_DIFF_ATTR": "x_dimer",
                    "E_THRES": 0.0,
                    "TORQ_THRES": 1.0e-2,
                    "F_THRES": 0.0,
                    "MAXITER_TRANS": 1,
                    "MAXITER_ROT": 1,
                    "MAX_STEPLENGTH": 0.01,
                    "DX": 1.0e-2,
                },
            },
            read_opt_structures,
        )
        self._assert_basic_structure_data(result)

    def test_md_command(self) -> None:
        """Run a two-step MD command and inspect its trajectory."""
        result = self._run_task(
            "MD",
            {
                "DATA_TYPE": "CIF",
                "DATA_PATH": self.cif_dir,
                "MD": {
                    "ENSEMBLE": "NVE",
                    "TIME_STEP": 0.1,
                    "MAX_STEP": 2,
                    "T_INIT": 10.0,
                    "OUTPUT_COORDS_PER_STEP": 1,
                    "MOVE_TO_CENTER_FREQ": -1,
                },
            },
            read_md_traj,
        )
        self._assert_basic_structure_data(result)

    def test_mc_command(self) -> None:
        """Run a two-iteration MC command and inspect its trajectory."""
        result = self._run_task(
            "MC",
            {
                "DATA_TYPE": "BS",
                "DATA_PATH": self.input_bs,
                "MC": {
                    "TYPE": "Metropolis",
                    "ITER_SCHEME": "Gaussian",
                    "COORDINATE_UPDATE_PARAM": 0.01,
                    "MAXITER": 2,
                    "T_INIT": 10.0,
                    "T_SCHEME": "constant",
                    "T_UPDATE_FREQ": 1,
                    "T_SCHEME_PARAM": 0.0,
                    "OUTPUT_COORDS_PER_STEP": 1,
                    "MOVE_TO_CENTER_FREQ": -1,
                },
            },
            read_mc_traj,
        )
        self._assert_basic_structure_data(result)

    def test_cmd_command(self) -> None:
        """Run a one-step Blue-Moon CMD command and inspect its trajectory."""
        result = self._run_task(
            "CMD",
            {
                "DATA_TYPE": "BS",
                "DATA_PATH": self.input_bs,
                "FSDATA_PATH": self.final_bs,
                "MD": {
                    "ENSEMBLE": "NVE",
                    "CONSTR_MD_SCHEME": "BLUE_MOON",
                    "N_IMAGES": 2,
                    "TIME_STEP": 0.1,
                    "MAX_STEP": 1,
                    "T_INIT": 10.0,
                    "OUTPUT_COORDS_PER_STEP": 1,
                    "MOVE_TO_CENTER_FREQ": -1,
                    "CONSTRAINTS_FILE": _CONSTRAINTS_FILE,
                    "CONSTRAINTS_FUNC": "first_pair_distance",
                },
            },
            read_md_traj,
        )
        self._assert_basic_structure_data(result)

    def test_cmd_slow_growth_command(self) -> None:
        """Run a one-step SLOW_GROWTH CMD command without a final-state file."""
        result = self._run_task(
            "CONSTR_MD",
            {
                "DATA_TYPE": "BS",
                "DATA_PATH": self.input_bs,
                "MD": {
                    "ENSEMBLE": "NVE",
                    "CONSTR_MD_SCHEME": "SLOW_GROWTH",
                    "N_IMAGES": 1,
                    "TIME_STEP": 0.1,
                    "MAX_STEP": 1,
                    "T_INIT": 10.0,
                    "OUTPUT_COORDS_PER_STEP": 1,
                    "MOVE_TO_CENTER_FREQ": -1,
                    "CONSTRAINTS_FILE": _CONSTRAINTS_FILE,
                    "CONSTRAINTS_FUNC": "first_pair_distance",
                    "CONSTRAINTS_VAL_FUNC": "first_pair_distance_target",
                },
            },
            read_md_traj,
        )
        self._assert_basic_structure_data(result)


if __name__ == "__main__":
    unittest.main()
